
import java.awt.image.BufferedImage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sunnny
 */
public class OutputImage extends javax.swing.JFrame {

    /**
     * Creates new form OutputImage
     */
    BufferedImage img;
    ZoomableImage image;
    public OutputImage(BufferedImage img) {
        initComponents();
        this.img=img;
        image=new ZoomableImage();
        image.setImage(img);
        imageSlider.setMajorTickSpacing(10);
        imageSlider.setMinorTickSpacing(1);
        imageSlider.setPaintTicks(true);
        imageSlider.setPaintLabels(true);
        this.add(image);
        setBounds(0,0,700,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(null);

        imageSlider.setBackground(new java.awt.Color(0, 204, 255));
        imageSlider.setForeground(new java.awt.Color(0, 153, 255));
        imageSlider.setMajorTickSpacing(1);
        imageSlider.setMinimum(1);
        imageSlider.setPaintTicks(true);
        imageSlider.setValue(100);
        imageSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                imageSliderStateChanged(evt);
            }
        });
        getContentPane().add(imageSlider);
        imageSlider.setBounds(160, 590, 460, 50);

        jLabel1.setText("Zoom In");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 600, 90, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_imageSliderStateChanged
      image.setScaleFactor((imageSlider.getValue()*1.0f/100));
      this.revalidate();
      this.repaint();
    }//GEN-LAST:event_imageSliderStateChanged

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider imageSlider;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
